// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fefuxnxwoeeafrvoscgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZnV4bnh3b2VlYWZydm9zY2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTI3NDUsImV4cCI6MjA2OTk4ODc0NX0.hVsCm2BopYHWo_dEDwsFgzxVtRJyEUgUD6ok6hIS2dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});